### ISSUE TITLE
support for 1.11.2 & 1.12 ?

### ISSUE THREAD

**Issue by smmmadden** [InventivetalentDev/SpigetUpdater#4]
I've been using the SpigotUpdater1.0..1.jar file for all my worlds and it works when I type in /version on each of the worlds to check for the latest build.  However, when I try to use the bungee-1.3.0.jar in the BungeeCord server plugin, it fails to startup.  The same is true for bukkit-1.3.0.jar file.

My assumption since it isn't spelled out here, is the bukkit-1.3.0.jar goes in the world\plugins folder and the bungee-1.3.0.jar goes in the bungeecord server plugins folder.  The only problem with both is there is no plugin.yml file included like the SpigotUpdater.jar file has, so how is this used?

**Comment by Derkades** [comment]
You probably won't need this question to be answered anymore, but for anyone else looking at this, it is meant to be shaded into your plugin.

**Comment by smmmadden** [comment]
shaded into your plugin?  what does that mean exactly?
