### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by SimplyBallistic** [InventivetalentDev/SpigetUpdater#6]
- Option to disable logging
- callback on fail checking for updating (Not fail on downloading)
- get update info (Update description etc.)
I will make a pull request if you are interested in accepting these changes.

**Comment by InventivetalentDev** [comment]
Sounds good!

**Comment by SimplyBallistic** [comment]
@InventivetalentDev I've made a pull request #7 adding the features in this list. Make sure to check them out.
